The Stock Synthesis 3 (SS3) assessment program provides a statistical framework for calibration of a population dynamics model using a diversity of fishery and survey data. SS is designed to deal with both age- and size-structure with multiple stock sub-areas and multiple growth patterns. The description here details the most commonly applied features, along with a subset of the more advanced options offered by SS3.

# Population Model

The factors described here are those that control the rate at which new individuals recruit to the population each time step; the rate at which they die due to fishing and natural mortality; and the rate at which they grow and contribute to the total biomass and reproductive potential of the stock. The total population can be divided among one to many entities. The total of all entities born within a year are referred to as a year-class or cohort. Each of the biologically- or birthseason- delineated entities is referred to as a morph. In addition, each morph can be sub-divided into slow-, medium-, and fast-growing entities termed platoons **(Goodyear 1996; Taylor and Methot 2012)**. The model description here does not include subscripting for morphs or platoons in an attempt for simplicity, but each of these entities is tracked in the population dynamics and biology if the user chooses to invoke these features. Each cohort/morph/platoon is split into males and females if the user invokes a two-sex configuration, and the subscript for gender is included in the description below.


