## Initial Numbers-at-Age

The population in the initial year of a SS application can be simply an unfished equilibrium population, a population in equilibrium with an estimated mortality rate that is influenced by data on historical equilibrium catch, or an equilibrium population that has estimable age-specific deviations from this equilibrium for a user-specified number of the younger ages.

The numbers of animals of sex $\gamma$ in age group a in a virgin state ($y=0$) is:

\begin{equation}
\label{eqn1}
N_{0,\gamma,a} =
\begin{cases}
cR_0e^{-aM_{\gamma,a}} & \text{for $a=0$ to $A-1$} \\
\sum_{a=A}^{3A-1}N_{0,\gamma,a} + \frac{N_{0,\gamma,3A-1}e^{-M_{\gamma,a}}}{1-e^{-M_{\gamma,a}}} & \text{for $a=A$ to $3A-1$}\\
\end{cases}
\end{equation}

where $c$ (I)[^1] is a user-defined constant that determines the sex-ratio of recruits[^2], $M_{\gamma,a}$ (P)[^3] is natural mortality for age a and sex $\gamma$, $A$ is the plus-group age, $3A$ is three times the plusgroup age, and $R_0$ is the number of age-0 fish at unfished equilibrium. The plus group virgin
numbers-at-age calculation is based on 3 timex the maximum age to include movement dynamics through age $3A-1$. After calculating the numbers-at-age through age $3A$, the numbers are collapsed to age A for subsequent calculations. Equation \ref{eqn1} use total mortality, $Z_{\gamma,a}$ (see Equation 1.21 XX), rather than $M_{\gamma,a}$ when the initial equilibrium also involves fishing mortality. Although this fishing mortality will reduce spawning biomass, no adjustment to $R_0$ is made on premise that this reduction has probably not been occurring for enough years to effect this change. $R_0$ serves as both the starting level of mean recruitment and as the factor that scales the mean spawner-recruitment relationship against which future annual recruitment deviations will act. An estimated offset, $R_1$, can be applied to $R_0$. When the initial population involves agespecific deviations, these deviations are an extension of the zero-centered, lognormal recruitment deviations applied to the equilibrium numbers-at-age (see Equation 1.20 XX).

[^1]: User-specified quantities will henceforth be denoted as "(I)". 
[^2]: The term "recruits" is used to refer to age-0 animals. 
[^3]: Estimated quantities will henceforth be denoted as "(P)".

## Recruitment

The number of age-0 fish is related to spawning biomass according to a stock-recruitment relationship. A range of stock-recruitment relationships are available. Here, the Beverton-Holt is described:

\begin{equation}
\label{eqn2}
R_y = \frac{4hR_0SB_y}{SB_0(1-h)+SB_y(5h-1)}e^{-0.5b_y\sigma_R^2+\tilde{R}_y} \;\ \tilde{R}_y \sim N(0; \sigma_R^2)
\end{equation}


where $R_0$ (P) is the unfished equilibrium recruitment, $SB_0$ is the unfished equilibrium spawning biomass (or spawning output) corresponding to $R_0$, $SB_y$ is the spawning biomass at the start of the spawning season
during year $y$, $h$ (P) is the steepness parameter, $b_y$ (I) is the bias adjustment fraction applied
during year $y$, $\sigma_R$ (P) is the standard deviation among recruitment deviations in log space, and
$\tilde{R}_y$ (P) is the lognormal recruitment deviation for year $y$. The bias-adjustment factor **(Methot
and Taylor 2011)** ensures unbiased estimation of mean recruitment even during data-poor eras in
which the maximum likelihood estimate of the $\tilde{R}_y$ is near 0.0.

The annual bias-adjustment fraction by $b_y$ is the piecewise linear function:

\begin{equation}
\label{eqn3}
b_y =
\begin{cases}
0 & \text{for $y \leq y_1^b$} \\
b_{\text{max}}(1-\frac{y-y_1^b}{y_2^b-y_1^b}) & \text{for $y_1^b < y < y_2^b$} \\
b_{\text{max}} & \text{for $y_2^b \leq y \leq y_3^b$} \\
b_{\text{max}}(1-\frac{y_3^b-y}{y_4^b-y_3^b}) & \text{for $y_3^b < y < y_4^b$} \\
0 & \text{for $y_4^b \leq y$} \\
\end{cases}
\end{equation}

where $y_1^b$ (I) is the first year of the bias ramp up adjustment period, $y_2^b$  (I) is the last year of the
bias ramp up adjustment period, $y_3^b$ (I) is the first year of the bias ramp down adjustment period,
$y_4^b$ (I) is the last year of the bias ramp down adjustment period, and $b_{\text{max}}$ (I) is the maximum bias adjustment applied to recruitment deviations.

The total annual recruitment can be partitioned among growth morphs and birth seasons and areas according to a design matrix. Each of these entities can be further divided into males and females according to a pre-specified fraction. Finally, each of these entities can be further subdivided into platoons that will have slow, medium or large size-at-age relative to the average size-at-age for the overall morph. For morphs that are designated to recruit in a season after the spawning season, their age 0 for the purposes of growth occurs at the start of that season. Thus, they will have smaller size-at-age relative to morphs of that annual cohort that are born earlier, but will grow towards the same $L_\infty$.

### Additional Stock Recruitment Relationship Functional Forms