name: update-release-with-small-changes

on:
  push:
  workflow_dispatch:

jobs:
  update-release-with-small-changes:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - name: Setup Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Ubuntu packages
        run: sudo apt-get update
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
     
       # Get Release     
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: install.packages("rmarkdown")
        shell: Rscript {0}

# Update version and date in SS330_User_Manual.tex
      - name: Update version and date in manual
        run: |
          manual_tex <- readLines("SS330_User_Manual.tex")
          date_line <- grep(pattern = "date\\{", x = manual_tex)
          todays_date <- format(x = Sys.Date(), "%B %d, %Y")
          manual_tex[date_line] <- gsub(
            pattern = "\\{[A-Za-z0-9, ]+",
            replacement = paste0("{", todays_date),
            x = manual_tex[date_line])
          writeLines(text = manual_tex, con = "SS330_User_Manual.tex")
        shell: Rscript {0}    
        
# Create HTML
      - name: Convert tex to html
        run: pandoc SS330_User_Manual.tex -s -o SS330_User_Manual.html --toc --embed-resources --standalone --mathjax --default-image-extension=png --number-sections --citeproc --variable linkcolor=#0033CC

      - name: Run R script to create html
        run: |
          source(".github/r_code/edit_html_improve_formatting.R")
          writeLines(html_txt, "docs/SS330_User_Manual_release.html")
          file.remove("SS330_User_Manual.html")
        shell: Rscript {0}  
        
# Commit tex and html changes
      - name: Commit changes of tex file version and html in docs folder to repo
        uses: EndBug/add-and-commit@v9
        with: 
          message: 'update html in docs with recent changes'

# Create PDF
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: SS330_User_Manual.tex
          latexmk_use_lualatex: true

 # Add PDF as artifact for previous release     
      - name: Upload release artifact - pdf manual
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./SS330_User_Manual.pdf
          asset_name: SS330_User_Manual.pdf
          asset_content_type: application/pdf

# Render user manuals to github pages
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs/